Production:
  ServerPort: 8080
  Apps:
  - AppHomePage: /
    AppBuildDir: /home/sreekar339/frontend/AppsDomainHomePage/static
    
  - AppHomePage: /YeezyMediaPlayer
    AppBuildDir: /home/sreekar339/frontend/CRA/YeezyMediaPlayer/build

  - AppHomePage: /Pikachu
    AppBuildDir: /home/sreekar339/frontend/CRA/Pikachu/build

Development:
  ServerPort: 8080
  Apps:
  - AppHomePage: /
    AppBuildDir: ./static

  - AppHomePage: /YeezyMediaPlayer
    AppBuildDir: /Users/sreekarnimbalkar/hobby_projs/media-player/build

  - AppHomePage: /Pikachu
    AppBuildDir: /Users/sreekarnimbalkar/pikachu/pikachu_frontend_web/build
  
